### ISSUE TITLE
Perplexity doesnt work at all

### ISSUE THREAD

**Issue by harishkm83** [SingularityLabs-ai/MultiGPT-mini#17]
perplexity integration doesnt work and no response at all. already logged in and im having a pro account

**To Reproduce**
just type a query and look at the perplexity response. 

**Expected behavior**
some response from perplexity ai

**Screenshots**
![image](https://github.com/SingularityLabs-ai/MultiGPT-mini/assets/97283806/309e8839-fdc2-436e-a0e0-f23a7c896c70)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser edge
 - Version latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ishandutta2007** [comment]
@harishkm83  is it working for you via poe.com directly ?

**Comment by Aaarkay1** [comment]
I am also facing this issue for a long time. I reported this bug here but developers do not seem to care. Just because it is working fine for them does not mean it is working fine for everyone else! Perplexity is  working fine on poe.com but not here!

**Comment by ishandutta2007** [comment]
@Aaarkay1 you have to tell the exact scenario or else we wont be able to help.

**Comment by ishandutta2007** [comment]
@Aaarkay1 POE related issue has been addrred some time back https://github.com/SingularityLabs-ai/MultiGPT-mini/issues/8 it it has not solved yours you should have mentioned there itself.
Anyway let us know all the details. (Browser, OS, Country, Type of router) let me see if we can find some lead from those.

**Comment by Aaarkay1** [comment]
@ishandutta2007 
Country - India
Browser - Brave
OS - Win 11
Router - TP Link

Here is a gif for demonstration
![1](https://github.com/SingularityLabs-ai/MultiGPT-mini/assets/63100754/ddfa8d03-d938-4c83-b2bf-521e241f268d)

**Comment by ishandutta2007** [comment]
@Aaarkay1 Ok can you help me debug. Can you run the following on your brave dev console and tell me the output. Check the [screencast](https://www.loom.com/share/0b7e8d7e5915457a96801008eb82b2c0?sid=2ac7a93c-bb6f-448d-a11d-18ad1b4bd4bf) in case you are not familiar on how to run a command on brave dev console.


`navigator.userAgent`

`

> 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

`

**Comment by ishandutta2007** [comment]
@Aaarkay1 Great !!! now as a second step open developer console again but now you have to open while using poe.com, now instead of console tab go to network tab, start a poe chat and then search `formkey` on left search panel and then tell me `Peo-Formkey`  number from right side.(ie wherever the search finds it)

See [screencast](https://www.loom.com/share/9f884f9d2fca48af86de2d0b11618b1b?sid=f0b18920-9c6c-4e96-bb87-09515b580bc4) for help.

**Comment by Aaarkay1** [comment]
@ishandutta2007 I get this number 7797682b245bb3c0aa386a8455580fa4

**Comment by ishandutta2007** [comment]
> 7797682b245bb3c0aa386a8455580fa4

@Aaarkay1 this is a new Poe-Formkey that we have not found in our testing so far.

> By the way, same exact issue is with Google PaLM as well.

If one poe bot has formkey issue all will have, they all use the same formkey.

**Comment by ishandutta2007** [comment]
For People whose poe.com bots are failing it may be so because your browser is not auto generating the formkey, 
we advice to explicitly add the formkey in settings page . Here is 
[Demo](https://www.loom.com/share/0026610ed2be4764a016892d3ee54589) for how to do it.

Meanwhile our team will continue to research on how to unobfuscate and run the formkey generation generation algorithm on client side.

**Comment by ishandutta2007** [comment]
Another issue perplexity has was intermittent failures which has also been fixed by moving from ```"perplexity_playground",{version: "2.1"}``` to ```"perplexity_labs", { version: "2.2"}```
