### ISSUE TITLE
Report: Disappearing and Glitchy Fields in MultiGPT Chrome Extension

### ISSUE THREAD

**Issue by MSotoudeh** [SingularityLabs-ai/MultiGPT-mini#33]
1- LLM title of each window in multi windows mode where we can choose one of the LLMs is changed to rigid rectangle.
2- There is a separated field under each of the windows, where we can chat with each of the LLMs independent of the main field, there are almost disappeared. So it is impossible to chat with one of opened grid windows independently.
3- I use Brave, but there is no difference if I turn off the brave shield.
4- I reinstall the extension but it is as same as before.
5- I can not install the previous version where is in the github.

- Brave [Version 1.65.123]
![Screenshot 2024-04-27 172608](https://github.com/SingularityLabs-ai/MultiGPT-mini/assets/96553249/9088d7b1-a2d8-4ab8-8741-6035e11a3a04)

**Comment by ishandutta2007** [comment]
1. You have to click on the title for dropdown to open. We just remove the down arrow button to save space as others said it is unnecessary.
2. It's by design . For separate chat you single window. no chats will be lost. The redesign is aimed removing redundant stuff so that maximum chat screen is visible.
3. It's doesn't have any ads or any trackers so brave shield wont have anything to block here.
4. You have the latest version already.
5. Use latest version please.

**Comment by ishandutta2007** [comment]
2. We will restore independent chats in next release. 
Currently we are busy with ChatGPT issues
